@echo off
echo Starting Leaderboard Backend Server...
echo.
cd backend
echo Installing dependencies...
npm install
echo.
echo Seeding database with initial users...
npm run seed
echo.
echo Starting development server...
npm run dev